# `params.yaml` - Pipeline parameters
fetch_data:
#  file: "cc.en.300.bin"
#  uri: "https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.en.300.bin.gz"
#  https://dl.fbaipublicfiles.com/fasttext/vectors-english/crawl-300d-2M-subword.zip
  file: crawl-300d-2M-subword.bin
  uri: https://dl.fbaipublicfiles.com/fasttext/vectors-english/crawl-300d-2M-subword.zip
fetch_model:
  file: lid.176.ftz
  uri: https://dl.fbaipublicfiles.com/fasttext/supervised-models/lid.176.ftz
prepare:
  # The embeddings file parameter is shared/borrowed from the `fetch_data` stage
  #  embeddings_file: "cc.en.300.bin"
  embeddings_dim: 300
  filter_lang_bool: true
  filter_lang: en
  lang_detect_model: lid.176.ftz
  stopwords_filter_lang: english
  filter_count_gteq: 2
  tfidf_dict_pickle_file: ''
  unknown_tag: UNK
train:
  seed: 31
  split: 0.7
  svm_regularization_C: 1
  svm_penalty: l2
  svm_loss: squared_hinge
  svm_dual: true
  use_pca: false
  num_components: 9
  class_types:
  - employer
  - occupation
  - UNK
  svm_kernel: linear
  svm_degree: 3
  svm_gamma: scale
  model_type: SVC
  knc_n_neighbors: 5
  knc_weights: uniform
  knc_algorithm: auto
  knc_leaf_size: 30
  knc_p: 2
  knc_metric: minkowski
relabel:
  # The number of folds to use in cross validation; 5 or 10 work well
  num_crossval_folds: 10
  # if min and max are none below, logging reports suitable values; data dependent
  min_distance_decision:
  max_distance_decision:
